### PR TITLE
feat: adding a new icon for Notebooks Flux merge

### PR DESCRIPTION
**Pull request by daviddkkim**
Closes # https://github.com/influxdata/clockface/issues/609

### Changes

// Describe what you changed
New Icon for Merge

### Screenshots
Screen Shot 2021-04-14 at 11 59 27 AM
Screen Shot 2021-04-14 at 12 08 13 PM

// Add screenshots here if relevant

### Checklist
Check all that apply

- [ ] Updated documentation to reflect changes
- [ ] Added entry to top of Changelog with link to PR (not issue)
- [ ] Tests pass
- [ ] Peer reviewed and approved
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

**Review by mavarius — COMMENTED** [review]
The icon looks a bit off-centered on the grid. This can cause blurring issues when resizing.

**Comment by daviddkkim** [comment]
Screen Shot 2021-04-14 at 12 24 41 PM
@mavarius

**Review by mavarius — APPROVED** [review]
Good to go!

**Comment by juliajames12** [comment]
Thanks @daviddkkim!

**Review by juliajames12 — COMMENTED** [review]
Thanks @daviddkkim!

**Pull request merged**
